version: '2'
services:
    factory-app:
        image: factory
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://factory-postgresql:5432/factory
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    factory-postgresql:
        extends:
            file: postgresql.yml
            service: factory-postgresql
